// src/app/navbar/navbar.component.ts
import {Component, OnInit} from '@angular/core';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="navbar bg-base-100">
  <a class="btn btn-ghost normal-case text-xl">Todo List App</a>
</div>

// src/components/Navbar.tsx
import clsx from 'clsx';

export default function Navbar() {
  return (
      <div className={clsx('Navbar',
          'navbar absolute top-0',
          'flex justify-between')}>
        <button className={'btn btn-ghost normal-case text-xl'}>
          Todo List App
        </button>
      </div>
  );
}
